spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: username1
    password: password1
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - order-schema.sql
      - ingredient-schema.sql
      - taco-schema.sql
      - user-schema.sql
    data:
      - ingredients.sql
